import type { SourcePlan, WorkOrder, WorkOrderProcess } from "./types";

const today = new Date();

export const sourcePlans: SourcePlan[] = [
  {
    id: 1,
    code: "PP-001",
    itemCode: "ITM-001",
    itemName: "태스크 체어",
    quantity: 200,
    startDate: toDateInput(addDays(today, 1)),
    endDate: toDateInput(addDays(today, 5)),
  },
  {
    id: 2,
    code: "PP-002",
    itemCode: "ITM-002",
    itemName: "회의 테이블",
    quantity: 80,
    startDate: toDateInput(addDays(today, 3)),
    endDate: toDateInput(addDays(today, 9)),
  },
  {
    id: 3,
    code: "PP-003",
    itemCode: "ITM-001",
    itemName: "태스크 체어",
    quantity: 120,
    startDate: toDateInput(addDays(today, 10)),
    endDate: toDateInput(addDays(today, 14)),
  },
];

export const initialOrders: WorkOrder[] = [
  {
    id: 1,
    code: "WO-001",
    planCode: "PP-001",
    itemCode: "ITM-001",
    itemName: "태스크 체어",
    quantity: 200,
    startDate: toDateInput(addDays(today, 1)),
    dueDate: toDateInput(addDays(today, 5)),
    workstation: "의자 조립 1라인",
    assignee: "김민준",
    status: "READY",
  },
  {
    id: 2,
    code: "WO-002",
    planCode: "PP-002",
    itemCode: "ITM-002",
    itemName: "회의 테이블",
    quantity: 80,
    startDate: toDateInput(addDays(today, 3)),
    dueDate: toDateInput(addDays(today, 9)),
    workstation: "테이블 조립 1라인",
    assignee: "박서연",
    status: "IN_PROGRESS",
  },
  {
    id: 3,
    code: "WO-003",
    planCode: "PP-003",
    itemCode: "ITM-001",
    itemName: "태스크 체어",
    quantity: 120,
    startDate: toDateInput(addDays(today, 10)),
    dueDate: toDateInput(addDays(today, 14)),
    workstation: "의자 조립 1라인",
    assignee: "이도윤",
    status: "HOLD",
  },
];

export const initialProcesses: WorkOrderProcess[] = [
  {
    id: 1,
    orderId: 1,
    sequence: 1,
    processCode: "PROC-001",
    processName: "자재 출고",
    workstation: "자재 창고",
    assignee: "김민준",
    startDate: toDateInput(addDays(today, 1)),
    dueDate: toDateInput(addDays(today, 1)),
    progress: 100,
    status: "COMPLETED",
  },
  {
    id: 2,
    orderId: 1,
    sequence: 2,
    processCode: "PROC-002",
    processName: "좌판 가공",
    workstation: "목공 1라인",
    assignee: "김민준",
    startDate: toDateInput(addDays(today, 2)),
    dueDate: toDateInput(addDays(today, 3)),
    progress: 60,
    status: "IN_PROGRESS",
  },
  {
    id: 3,
    orderId: 1,
    sequence: 3,
    processCode: "PROC-003",
    processName: "프레임 조립",
    workstation: "의자 조립 1라인",
    assignee: "최하윤",
    startDate: toDateInput(addDays(today, 4)),
    dueDate: toDateInput(addDays(today, 4)),
    progress: 0,
    status: "READY",
  },
  {
    id: 9,
    orderId: 1,
    sequence: 4,
    processCode: "PROC-009",
    processName: "검사/포장",
    workstation: "검사 포장실",
    assignee: "정검사",
    startDate: toDateInput(addDays(today, 5)),
    dueDate: toDateInput(addDays(today, 5)),
    progress: 0,
    status: "READY",
  },
  {
    id: 4,
    orderId: 2,
    sequence: 1,
    processCode: "PROC-004",
    processName: "자재 출고",
    workstation: "자재 창고",
    assignee: "박서연",
    startDate: toDateInput(addDays(today, 3)),
    dueDate: toDateInput(addDays(today, 3)),
    progress: 100,
    status: "COMPLETED",
  },
  {
    id: 5,
    orderId: 2,
    sequence: 2,
    processCode: "PROC-005",
    processName: "상판 재단",
    workstation: "목공 2라인",
    assignee: "박서연",
    startDate: toDateInput(addDays(today, 4)),
    dueDate: toDateInput(addDays(today, 6)),
    progress: 45,
    status: "IN_PROGRESS",
  },
  {
    id: 6,
    orderId: 2,
    sequence: 3,
    processCode: "PROC-006",
    processName: "엣지 밴딩",
    workstation: "엣지 밴딩기",
    assignee: "최하윤",
    startDate: toDateInput(addDays(today, 7)),
    dueDate: toDateInput(addDays(today, 8)),
    progress: 0,
    status: "READY",
  },
  {
    id: 10,
    orderId: 2,
    sequence: 4,
    processCode: "PROC-010",
    processName: "프레임 조립",
    workstation: "테이블 조립 1라인",
    assignee: "박서연",
    startDate: toDateInput(addDays(today, 9)),
    dueDate: toDateInput(addDays(today, 9)),
    progress: 0,
    status: "READY",
  },
  {
    id: 7,
    orderId: 3,
    sequence: 1,
    processCode: "PROC-007",
    processName: "가스 리프트 입고 대기",
    workstation: "자재 창고",
    assignee: "이도윤",
    startDate: toDateInput(addDays(today, 10)),
    dueDate: toDateInput(addDays(today, 10)),
    progress: 0,
    status: "HOLD",
  },
  {
    id: 8,
    orderId: 3,
    sequence: 2,
    processCode: "PROC-008",
    processName: "의자 조립",
    workstation: "의자 조립 1라인",
    assignee: "이도윤",
    startDate: toDateInput(addDays(today, 11)),
    dueDate: toDateInput(addDays(today, 13)),
    progress: 0,
    status: "READY",
  },
  {
    id: 11,
    orderId: 3,
    sequence: 3,
    processCode: "PROC-011",
    processName: "검사/포장",
    workstation: "검사 포장실",
    assignee: "정검사",
    startDate: toDateInput(addDays(today, 14)),
    dueDate: toDateInput(addDays(today, 14)),
    progress: 0,
    status: "READY",
  },
];

export function makeDefaultProcesses({
  orderId,
  startDate,
  dueDate,
  workstation,
  assignee,
  nextProcessId,
}: {
  orderId: number;
  startDate: string;
  dueDate: string;
  workstation: string;
  assignee: string;
  nextProcessId: number;
}): WorkOrderProcess[] {
  return [
    {
      id: nextProcessId,
      orderId,
      sequence: 1,
      processCode: `PROC-${String(nextProcessId).padStart(3, "0")}`,
      processName: "자재 출고",
      workstation: "자재 창고",
      assignee,
      startDate,
      dueDate: startDate,
      progress: 0,
      status: "READY",
    },
    {
      id: nextProcessId + 1,
      orderId,
      sequence: 2,
      processCode: `PROC-${String(nextProcessId + 1).padStart(3, "0")}`,
      processName: "조립",
      workstation,
      assignee,
      startDate,
      dueDate,
      progress: 0,
      status: "READY",
    },
    {
      id: nextProcessId + 2,
      orderId,
      sequence: 3,
      processCode: `PROC-${String(nextProcessId + 2).padStart(3, "0")}`,
      processName: "검사/포장",
      workstation: "검사 포장실",
      assignee: "미지정",
      startDate: dueDate,
      dueDate,
      progress: 0,
      status: "READY",
    },
  ];
}

export function addDays(date: Date, days: number) {
  const next = new Date(date);
  next.setDate(next.getDate() + days);
  return next;
}

export function toDateInput(date: Date) {
  return date.toISOString().slice(0, 10);
}
