"use client";

import { useEffect, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { lotQualityApi, type QualityStandard, type QualityStandardInput } from "@/entities/lot-quality";
import { productApi } from "@/entities/product";
import { getErrorMessage } from "@/shared/api/errors";

type Form = { productId: string; standardName: string; version: string; minimumYieldRate: string; minimumGoodQuantity: string; description: string };
const empty = (): Form => ({ productId: "", standardName: "", version: "1", minimumYieldRate: "98", minimumGoodQuantity: "2000", description: "" });

export function LotQualityStandardManagement() {
  const client = useQueryClient(); const [selected, setSelected] = useState<QualityStandard | null>(null); const [form, setForm] = useState<Form>(empty());
  const standards = useQuery({ queryKey: ["lot-quality-standards"], queryFn: lotQualityApi.getAll }); const products = useQuery({ queryKey: ["products"], queryFn: productApi.getProducts });
  const refresh = () => client.invalidateQueries({ queryKey: ["lot-quality-standards"] });
  useEffect(() => { if (selected) setForm({ productId: String(selected.productId), standardName: selected.standardName, version: String(selected.version), minimumYieldRate: selected.minimumYieldRate == null ? "" : String(selected.minimumYieldRate), minimumGoodQuantity: selected.minimumGoodQuantity == null ? "" : String(selected.minimumGoodQuantity), description: selected.description ?? "" }); }, [selected]);
  const save = useMutation({ mutationFn: () => selected ? lotQualityApi.update(selected.id, input(form)) : lotQualityApi.create(input(form)), onSuccess: async () => { await refresh(); toast.success("LOT 품질 기준을 저장했습니다."); }, onError: (e) => toast.error(getErrorMessage(e, "저장하지 못했습니다.")) });
  const remove = useMutation({ mutationFn: lotQualityApi.delete, onSuccess: async () => { await refresh(); setSelected(null); setForm(empty()); toast.success("초안 기준을 삭제했습니다."); }, onError: (e) => toast.error(getErrorMessage(e, "초안 기준만 삭제할 수 있습니다.")) });
  const submit = (e: FormEvent) => { e.preventDefault(); if (!form.productId || !form.standardName.trim()) return; save.mutate(); };
  const create = () => { setSelected(null); setForm(empty()); };
  return <main className="min-h-[calc(100vh-3.5rem)] bg-muted/20 px-4 py-8 sm:px-8 lg:px-10"><section className="mx-auto max-w-7xl"><header className="flex items-end justify-between border-b pb-7"><div><p className="text-xs font-bold tracking-[.18em] text-primary">LOT QUALITY · RELEASE GATE</p><h1 className="mt-3 text-3xl font-bold">LOT 품질 기준</h1><p className="mt-2 text-sm text-muted-foreground">완료 상태, 최소 수율, 최소 정상 수량으로 LOT 출하 기준을 관리합니다.</p></div><button onClick={create} className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-bold text-primary-foreground"><Plus className="h-4 w-4" />기준 등록</button></header>
    <div className="mt-6 overflow-hidden rounded-xl border bg-card shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[52rem] text-sm"><thead className="bg-muted/30 text-left text-xs text-muted-foreground"><tr><Th>제품</Th><Th>기준명</Th><Th>버전</Th><Th>대상 LOT 상태</Th><Th>최소 수율</Th><Th>최소 정상 수량</Th><Th>상태</Th></tr></thead><tbody>{standards.data?.map((row) => <tr key={row.id} onClick={() => setSelected(row)} className={`cursor-pointer border-t hover:bg-muted/30 ${selected?.id === row.id ? "bg-primary/5" : ""}`}><Td>{row.productCode}</Td><Td className="font-semibold">{row.standardName}</Td><Td>v{row.version}</Td><Td>완료</Td><Td>{row.minimumYieldRate == null ? "미설정" : `${row.minimumYieldRate}% 이상`}</Td><Td>{row.minimumGoodQuantity == null ? "미설정" : `${row.minimumGoodQuantity.toLocaleString()} EA 이상`}</Td><Td><Status value={row.status} /></Td></tr>)}</tbody></table></div>{!standards.data?.length && <p className="p-8 text-center text-sm text-muted-foreground">등록된 LOT 품질 기준이 없습니다.</p>}</div>
    <form onSubmit={submit} className="mt-6 rounded-xl border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">{selected ? "LOT 품질 기준 수정" : "LOT 품질 기준 등록"}</h2><p className="mt-1 text-xs text-muted-foreground">완료 상태, 최소 수율, 최소 정상 수량으로 통과 여부를 판단합니다.</p></div>{selected?.status === "DRAFT" && <button type="button" onClick={() => remove.mutate(selected.id)} className="rounded p-2 text-muted-foreground hover:text-destructive"><Trash2 className="h-4 w-4" /></button>}</div><div className="mt-5 grid gap-3 md:grid-cols-3"><Field label="적용 제품"><select className="field" disabled={!!selected} value={form.productId} onChange={(e) => setForm({ ...form, productId: e.target.value })}><option value="">제품 선택</option>{products.data?.filter((p) => p.active).map((p) => <option key={p.id} value={p.id}>{p.productCode} · {p.productName}</option>)}</select></Field><Field label="기준명"><input className="field" disabled={selected?.status !== undefined && selected.status !== "DRAFT"} value={form.standardName} onChange={(e) => setForm({ ...form, standardName: e.target.value })} /></Field><Field label="버전"><input className="field" type="number" disabled={!!selected} value={form.version} onChange={(e) => setForm({ ...form, version: e.target.value })} /></Field><Field label="LOT 상태"><input className="field bg-muted" disabled value="완료" /></Field><Field label="최소 수율"><input className="field" disabled={selected?.status !== undefined && selected.status !== "DRAFT"} type="number" min="0" max="100" step="0.1" value={form.minimumYieldRate} onChange={(e) => setForm({ ...form, minimumYieldRate: e.target.value })} /></Field><Field label="최소 정상 수량"><input className="field" disabled={selected?.status !== undefined && selected.status !== "DRAFT"} type="number" min="0" value={form.minimumGoodQuantity} onChange={(e) => setForm({ ...form, minimumGoodQuantity: e.target.value })} /></Field></div><Field label="설명"><input className="field mt-1" disabled={selected?.status !== undefined && selected.status !== "DRAFT"} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field>{selected?.status === "APPROVED" ? <p className="mt-5 rounded-lg bg-muted p-3 text-sm text-muted-foreground">승인된 기준은 읽기 전용입니다.</p> : <div className="mt-5 flex justify-end"><button disabled={save.isPending} className="h-10 rounded-lg bg-primary px-4 text-sm font-bold text-primary-foreground">저장</button></div>}</form></section></main>;
}
function input(f: Form): QualityStandardInput { return { productId: Number(f.productId), standardName: f.standardName.trim(), version: Number(f.version), requiredLotStatus: "DONE", minimumYieldRate: Number(f.minimumYieldRate), minimumGoodQuantity: Number(f.minimumGoodQuantity), passDisposition: "SHIP", failDisposition: "HOLD", description: f.description.trim() || undefined }; }
function Status({ value }: { value: string }) { return <span className="rounded-full bg-muted px-2 py-1 text-[10px] font-bold">{value}</span>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-bold text-muted-foreground">{label}<span className="mt-1 block [&_.field]:h-10 [&_.field]:w-full [&_.field]:rounded-lg [&_.field]:border [&_.field]:border-input [&_.field]:bg-background [&_.field]:px-3 [&_.field]:text-sm [&_.field]:font-normal [&_.field]:text-foreground">{children}</span></label>; }
function Th({ children }: { children: React.ReactNode }) { return <th className="px-4 py-3 font-semibold">{children}</th>; }
function Td({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <td className={`px-4 py-3 ${className}`}>{children}</td>; }
