import { ArrowRight, ClipboardCheck, ClipboardList, Factory, Layers3, ListChecks, Loader2, RefreshCw } from "lucide-react";
import { Link } from "react-router-dom";
import { useDashboard } from "../features/dashboard/model/useDashboard";
import { useQualityInspections } from "../features/quality-inspection/model/useQualityInspections";

export default function DashboardPage() {
  const dashboard = useDashboard();
  const qualityInspections = useQualityInspections();
  const summary = dashboard.data;
  const waitingInspections = qualityInspections.data?.filter((inspection) => inspection.status === "WAITING").length;
  const cards = [
    { label: "전체 LOT", value: summary ? `${summary.totalLots}개` : "-", detail: `진행 중 ${summary?.activeLots ?? "-"}개`, Icon: Layers3, to: "/lots" },
    { label: "완료 작업지시", value: summary ? `${summary.completedWorkOrders}개` : "-", detail: `전체 ${summary?.totalWorkOrders ?? "-"}개`, Icon: ListChecks, to: "/work-orders" },
    { label: "검사 대기", value: waitingInspections == null ? "-" : `${waitingInspections}건`, detail: "품질 검사 결과 입력 필요", Icon: ClipboardCheck, to: "/quality-inspections" },
  ];

  return <div className="space-y-6">
    <header className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-sky-600">PKT PRACTICE LAB</p><h1 className="mt-2 text-3xl font-black tracking-tight">프론트 실습 대시보드</h1><p className="mt-2 text-sm font-semibold text-slate-500">실제 MES API 데이터를 카드와 최근 LOT 목록으로 확인합니다.</p></div><button type="button" onClick={() => void Promise.all([dashboard.refetch(), qualityInspections.refetch()])} disabled={dashboard.isFetching || qualityInspections.isFetching} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-bold text-slate-600 transition hover:border-sky-300 hover:text-sky-700 disabled:opacity-50"><RefreshCw className={`size-4 ${dashboard.isFetching || qualityInspections.isFetching ? "animate-spin" : ""}`} />새로고침</button></header>
    {dashboard.isPending || qualityInspections.isPending ? <div className="flex items-center justify-center rounded-2xl border border-slate-200 bg-white p-12 text-sm font-bold text-slate-500"><Loader2 className="mr-2 size-4 animate-spin" />대시보드 데이터를 불러오는 중입니다…</div> : dashboard.isError || qualityInspections.isError ? <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm font-bold text-red-700">{dashboard.error?.message ?? qualityInspections.error?.message}</div> : <>
      <div className="grid gap-4 md:grid-cols-3">{cards.map(({ label, value, detail, Icon, to }) => <Link key={label} to={to} className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:border-sky-300 hover:shadow-sm"><Icon className="size-5 text-sky-600" /><p className="mt-5 text-sm font-bold text-slate-500">{label}</p><p className="mt-1 text-xl font-black">{value}</p><p className="mt-1 text-xs font-semibold text-slate-400">{detail}</p></Link>)}</div>
      <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-sky-600">LOT STATUS</p><h2 className="mt-1 text-lg font-black">LOT 현황</h2></div><Factory className="size-5 text-sky-600" /></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">전체</p><p className="mt-1 text-2xl font-black">{summary?.totalLots}개</p></div><div className="rounded-xl bg-sky-50 p-4"><p className="text-xs font-bold text-sky-600">진행 중</p><p className="mt-1 text-2xl font-black text-sky-700">{summary?.activeLots}개</p></div><div className="rounded-xl bg-emerald-50 p-4"><p className="text-xs font-bold text-emerald-600">완료</p><p className="mt-1 text-2xl font-black text-emerald-700">{summary?.completedLots}개</p></div></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-sky-600">LATEST LOTS</p><h2 className="mt-1 text-lg font-black">최근 LOT</h2></div><ClipboardList className="size-5 text-sky-600" /></div><div className="mt-3 divide-y divide-slate-100">{summary?.latestLots.map((lot) => <Link key={lot.id} to="/lots" className="flex items-center justify-between gap-3 py-3 text-sm hover:text-sky-700"><span className="font-black">{lot.id}</span><span className="text-slate-500">{lot.product}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{lot.status}</span></Link>)}</div></section></div>
      <Link to="/lots" className="flex items-center justify-between rounded-2xl bg-sky-700 p-6 text-white"><div><p className="text-sm font-bold text-sky-100">첫 번째 실습</p><p className="mt-1 text-xl font-black">LOT 목록 테이블 만들기</p></div><ArrowRight className="size-5" /></Link>
    </>}
  </div>;
}
